sudo: false
language: cpp
matrix:
  include:
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - doxygen
            - graphviz
            - help2man
            - python-docutils
            - pngcrush
            - python-sphinx
            - uuid-dev
            - libpcre3-dev
            - libmagic-dev
            - tcl
            - libsvm-dev
            - gcc-4.9
            - g++-4.9
      compiler: gcc
    - compiler: clang
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - doxygen
            - graphviz
            - help2man
            - python-docutils
            - pngcrush
            - python-sphinx
            - uuid-dev
            - libpcre3-dev
            - libmagic-dev
            - tcl
            - libsvm-dev
            - libc++-dev
      compiler: clang
env:
  - XAPIAN_COMMON_CLONE_URL=https://github.com/xapian/xapian.git
before_script:
  - ./bootstrap xapian-core xapian-applications/omega swig xapian-bindings xapian-letor
  - ./configure
script: make && make check
