# Travis configuration for building Xapian. This is fairly intensive, so
# we only enable it for pull requests.
#
# Right now, we build on containerised linux, which defaults to the
# ancient Ubuntu 12.04 LTS.  Specify "dist: trusty" so we get something
# which is "only" 2.5 years old.
dist: trusty
sudo: false
language: cpp
env:
  global:
    # Tell bootstrap where to clone ./common from
    - XAPIAN_COMMON_CLONE_URL=https://github.com/xapian/xapian.git
    - HOMEBREW_PACKAGES='doxygen help2man graphviz pngcrush libmagic pcre libsvm lua mono python2 python'
matrix:
  include:
    - compiler: gcc
      os: linux
      addons:
        apt:
          packages:
            - doxygen
            - graphviz
            - help2man
            - python-docutils
            - pngcrush
            - python-sphinx
            - uuid-dev
            - libpcre3-dev
            - libmagic-dev
            - lua5.2
            - liblua5.2-dev
            - mono-devel
            - python-dev
            - python3-dev
            - tcl
            - libsvm-dev
    - compiler: clang
      os: linux
      # Clang is already installed, but we want to build using the
      # llvm c++ library, not the GCC one. (Otherwise, depending on
      # the GCC version, there can be issues.)
      addons:
        apt:
          packages:
            - doxygen
            - graphviz
            - help2man
            - python-docutils
            - pngcrush
            - python-sphinx
            - uuid-dev
            - libpcre3-dev
            - libmagic-dev
            - tcl
            - libsvm-dev
            - libc++-dev
      # We also have to disable an error, because (older?)
      # perl header files don't play nicely with clang.
      env: USE_CC=clang USE_CXX='clang++ -stdlib=libc++' CXXFLAGS=-Wno-error=reserved-user-defined-literal
    - os: osx
      before_install:
        - brew update
        # python is now python3, but the travis macOS build isn't there yet
        # so we need to explicitly upgrade otherwise we end up with the old
        # python (which is 2.7.x) and the python2 package (which is also
        # 2.7.x). This step can be removed once travis ships with a more
        # recent homebrew.
        - brew upgrade python
        # "brew install" unhelpfully errors out if any package listed is
        # already installed and up-to-date, but travis change what's installed
        # by default from time to time so it's brittle to just filter out those
        # installed by default from the list we need.  Instead we ignore the
        # exit status from "brew install", then check later that
        # "brew list --versions" says all the packages requested are installed.
        - brew install $HOMEBREW_PACKAGES || true
        - brew list --versions $HOMEBREW_PACKAGES
        - /usr/local/opt/python@2/libexec/bin/pip install sphinx docutils
        - pip install sphinx
        - mkdir -p /tmp/xapian-libsvm-fixed-include
        - ln -sF "`ls -1d /usr/local/Cellar/libsvm/3.*/include|tail -n 1`" /tmp/xapian-libsvm-fixed-include/libsvm
      env: PYTHON2=/usr/local/opt/python@2/libexec/bin/python CXXFLAGS=-Wno-error=reserved-user-defined-literal CPPFLAGS=-I/tmp/xapian-libsvm-fixed-include confargs=--prefix=/Users/travis/XapianInstall installcore='make -C xapian-core install'
    - os: linux
      # (Ab)use env to label this build:
      env: dummy="Automated run of xapian-check-patch"
      # Override before_script to do nothing
      before_script:
      # Override script to diff from against the branch point from:
      # * for a PR, the branch the PR targets
      # * otherwise, master
      script:
        - git diff `[ "$TRAVIS_PULL_REQUEST" = false ] && echo master || echo "$TRAVIS_BRANCH"`...|xapian-maintainer-tools/xapian-check-patch


before_script:
  # Bootstrap everything (including letor, which isn't done
  # by default), then configure using our chosen compiler.
  - ./bootstrap xapian-core xapian-applications/omega swig xapian-bindings xapian-letor
  - ./configure $confargs CC="$USE_CC" CXX="$USE_CXX"
script:
  - make
  - $installcore
  - make check VERBOSE=1 AUTOMATED_TESTING=1
  - test -z "`git status --porcelain=v1`" || { echo "Generated files not in .gitignore:" ; git status ; exit 1; }
