#!/bin/sh
${LIBTOOL-../libtool} --config > libtoolconfig.$$
. ./libtoolconfig.$$
rm -f libtoolconfig.$$
module=yes
eval shlibext=$shrext_cmds

tclshlibext=`echo 'puts [info sharedlibextension]'|${TCLSH-tclsh}`

rm -f xapian$tclshlibext
ln -s $objdir/xapian$shlibext xapian$tclshlibext
DYLD_LIBRARY_PATH="$INTREE_DYLD_PATH" ${TCLSH-tclsh} ${srcdir-.}/runtest.tcl ${srcdir-.}/smoketest.tcl
rc=$?
rm -f xapian$tclshlibext
exit $rc
